/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.0/samples
 */

plugins {
    kotlin("jvm") version "1.5.0"
    kotlin("jupyter.api") version "0.10.0-13"

    // publish to maven (only local repo for now)
    `maven-publish`
}

dependencies {
    implementation("black.ninia:jep:3.9.1")
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["kotlin"])
            pom {
                url.set("https://github.com/hanslovsky/jepyter")
                inceptionYear.set("2021")
                licenses {
                    license {
                        name.set("Simplified BSD License")
                        distribution.set("repo")
                    }
                }
                scm {
                    connection.set("scm:git:git://github.com/hanslovsky/jepyter")
                    developerConnection.set("scm:git:git@github.com:hanslovsky/jepyter")
                    tag.set("HEAD")
                    url.set("https://github.com/hanslovsky/jepyter")
                }
                ciManagement {
                    system.set("Travis CI")
                    url.set("https://travis-ci.com/hanslovsky/jepyter")
                }
//                repositories {
//                    add(maven("https://maven.scijava.org/content/groups/public"))
//                }
//                withXml {
//                    asNode()
//                        .appendNode("repositories")
//                        .appendNode("repository").also {
//                            it.appendNode("id", "scijava.public")
//                            it.appendNode("url", "https://maven.scijava.org/content/groups/public")
//                        }
////                            .appendNode("scijava.public", "https://maven.scijava.org/content/groups/public")
//                }
            }
        }
    }
}